"""empty message

Revision ID: 14270af28389
Revises: 
Create Date: 2022-08-11 20:00:54.985755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14270af28389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('searching_artist', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('past_shows', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('searching_venue', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'desc')
    op.drop_column('Venue', 'searching_venue')
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'past_shows')
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Artist', 'desc')
    op.drop_column('Artist', 'searching_artist')
    op.drop_column('Artist', 'website')
    op.drop_table('Show')
    # ### end Alembic commands ###
